In [1]:
# this notebook is perform anaylsis of MACE events in the care home hypertension cohort

In [2]:
library(ggplot2)
library(bigrquery)
library(tidyverse)
library(ggplot2)
library(lubridate)
library(stats)

ProjectId = "yhcr-prd-bradfor-bia-core"

targetdb1 <-'yhcr-prd-bradfor-bia-core.CB_MYSPACE_MK'
targetdb1 <-gsub(' ','',targetdb1)

targetdb2 <- 'yhcr-prd-bradfor-bia-core.CB_FDM_DeathCertificates'
targetdb2 <-gsub(' ','',targetdb2)

targetdb3 <- 'yhcr-prd-bradfor-bia-core.CB_2172'
targetdb3 <- gsub(' ','',targetdb3)

In [33]:
sql1 <- 
paste(
    'SELECT  *
from ',targetdb3,'.cb_2172_mace 
where person_id in(select person_id from ',targetdb3,'.care_home_cohort_v1) 
;',sep="")

mace_tbl <-bq_project_query(ProjectId,sql1)
mace_data <- bq_table_download(mace_tbl)
#filter out any individuals where the time between admission and death is less than 42 days

In [34]:
mace_data$date.event <- as.Date(mace_data$dod)

mace_data <- mace_data %>% select(-dod)

In [35]:
mace_data <- mace_data %>% arrange(person_id, desc(date.event)) %>% mutate(event_id= rank(date.event
                                                                                        ))
#here is the initial data, the problem is there are some  duplicate events where the data differs by only a couple of days so they are counted as different events. 
#Some cardiovasccular deaths also have  the cardiovascular event (e.g. myocardial evvent,
#recorded as a seperate event a few days apart). I need to remove these events so that only the cardiovascular death is recorded. 
#This is based on the assumption that where a stroke or MI has been recorded within 30 days of a cardiovascular death, 
# the two are realted and therefore the stroke or MI was a fatal one so should be recorded as a CV death 
#rather than a non fatal MI or stroke.

    person_id event_type            date.event event_id
1     339912  cv death              2017-12-15  70.5
2     533373  cv death              2017-11-15  63.5
3     576388  cv death              2019-10-15 170.0
4     706765  cv death              2019-03-15 133.5
5     879366  cv death              2019-06-15 154.0
6     879366  myocardial infarction 2019-06-10 151.0
7     899131  myocardial infarction 2020-05-26 191.0
8     899131  cv death              2020-05-15 190.0
9   12388259  cv death              2017-02-15  16.5
10  12390501  cv death              2019-07-15 160.5
11  12394871  myocardial infarction 2019-03-15 133.5
12  12394871  myocardial infarction 2019-03-12 130.0
13  12398061  cv death              2018-09-15 103.5
14  12401518  stroke                2017-05-02  31.0
15  12402870  myocardial infarction 2017-10-26  60.0
16  12406005  cv death              2017-10-15  58.0
17  12415453  myocardial infarction 2017-06-24  45.0
18  12421727  cv death              2020-01-15 179.5
19  12427943  cv death              2019-05-15 148.5
20  12429242  stroke                2020-02-21 183.0
21  12429724  cv death              2019-11-15 174.0
22  12437211  cv death              2017-02-15  16.5
23  12441334  cv death              2017-06-15  40.0
24  12443495  cv death              2019-01-15 122.5
25  12449343  myocardial infarction 2019-02-28 128.0
26  12449857  cv death              2017-09-15  54.0
27  12451603  cv death              2020-04-15 189.0
28  12455482  myocardial infarction 2016-12-05   7.0
29  12458587  myocardial infarction 2019-12-23 178.0
30  12470232  cv death              2017-03-15  23.0
⋮   ⋮         ⋮                     ⋮          ⋮
165 13542748  cv death              2017-06-15  40.0
166 13555576  stroke                2019-07-05 157.0
167 13576861  stroke                2017-06-19  44.0
168 13576950  stroke                2020-03-28 188.0
169 13580091  cv death              2018-07-15  96.0
170 13580091  myocardial infarction 2018-05-07  90.0
171 13580202  myocardial infarction 2016-06-07   2.0
172 13580202  myocardial infarction 2016-06-06   1.0
173 13583345  stroke                2017-10-01  56.0
174 13586529  stroke                2019-02-08 124.0
175 13596832  stroke                2017-06-13  36.0
176 13621165  myocardial infarction 2017-09-04  52.0
177 13622104  cv death              2018-12-15 118.5
178 13633332  cv death              2019-05-15 148.5
179 13638262  cv death              2017-06-15  40.0
180 13670902  myocardial infarction 2019-08-18 164.0
181 13676724  cv death              2018-11-15 113.5
182 13679402  cv death              2018-10-15 110.5
183 13679557  stroke                2018-12-06 116.0
184 13687907  cv death              2018-08-15  99.5
185 13688187  cv death              2018-04-15  87.0
186 13700374  cv death              2018-10-15 110.5
187 13706066  stroke                2017-03-27  26.0
188 13711038  cv death              2017-02-15  16.5
189 13712846  cv death              2017-12-15  70.5
190 13723011  cv death              2018-07-15  96.0
191 13723242  cv death              2017-04-15  29.0
192 13723242  stroke                2017-02-25  20.0
193 13730554  cv death              2017-01-15  12.0
194 13751806  stroke                2018-03-08  83.5

In [36]:
# this identifies myocardial infarction events where another event occurs afterwards
# (either a duplicate event or death), so these myocardial events can be removed, 
#i will do the same for stroke as well. this ensures only non fatal myocardial infarctions 
# and strokes are captured in the MACE outcomes. fatal myocardial infarctions and stroke would fall into CV death 
mace_data_filtered_mi_cvd <- mace_data %>%
  group_by(person_id) %>% 
filter(event_type == 'myocardial infarction' & !((date.event - lag(date.event)) >= 30 &
                                                 (date.event - lag(date.event)) > 0)) %>%
  ungroup() 

mace_data_filtered_mi_cvd

  person_id event_type            date.event event_id
1   879366  myocardial infarction 2019-06-10 151.0
2 12394871  myocardial infarction 2019-03-12 130.0
3 12755225  myocardial infarction 2019-07-06 158.5
4 12831720  myocardial infarction 2018-01-09  74.0
5 13580091  myocardial infarction 2018-05-07  90.0
6 13580202  myocardial infarction 2016-06-06   1.0

In [37]:
mace_data <- mace_data %>% arrange(person_id, desc(date.event))


# this identifies stroke events where another event occurs afterwards(either a duplicate event or death), so these myocardial events can be removed, i will do the same for stroke as well. this ensures only non fatal myocardial infarctions and strokes are captured in the MACE outcomes. fatal myocardial infarctions and stroke would fall into CV death 
mace_filtered_stroke_cvd <- mace_data %>%
  group_by(person_id) %>% filter(event_type == 'stroke' & !((date.event - lag(date.event)) >= 30 & (date.event - lag(date.event)) > 0)) %>%
  ungroup() 

mace_filtered_stroke_cvd

  person_id event_type date.event event_id
1 12921291  stroke     2016-12-29  10
2 13066369  stroke     2019-09-03 165
3 13424129  stroke     2019-05-13 146
4 13494181  stroke     2017-11-17  66
5 13723242  stroke     2017-02-25  20

In [38]:
#i then subsetted the mace_Data to remove those duplicate stroke and myocardial events identified above

In [39]:
#creat he not in function

'%notin%' <- Negate(`%in%`)

In [40]:
mace_data_filtered <- mace_data[mace_data$event_id %notin% mace_data_filtered_mi_cvd$event_id, ]

In [41]:
mace_data_filtered <- mace_data_filtered[mace_data_filtered$date.event %notin% mace_filtered_stroke_cvd$date.event,]

In [53]:
mace_data_filtered <- mace_data_filtered %>% arrange(person_id, desc(date.event))

table(mace_data_filtered$event_type)

             cv death myocardial infarction                stroke
                  110                    17                    55

In [43]:
# merge the care home cohort table in order to calculate the incidence density
#(need to subset by the cae_home_cohort_v1 table as cohort was updated in feb 2025, to exclude people with no follow-up

In [44]:
sql1 <- 
paste(
    'SELECT person_id,first_episodestartdate, hypertension
from ',targetdb3,'.cb_2172_hypertension_combined 
where person_id in(select person_id from ',targetdb3,'.care_home_cohort_v1)
;',sep="")

bp_tbl <-bq_project_query(ProjectId,sql1)
ch_cohort <- bq_table_download(bp_tbl)

ch_cohort$person_id <- as.character(ch_cohort$person_id)
print(ch_cohort)

# A tibble: 2,774 × 3
   person_id first_episodestartdate hypertension
   <chr>     <dttm>                 <lgl>
 1 13391566  2016-04-08 00:00:00    FALSE
 2 13407837  2016-05-16 00:00:00    FALSE
 3 13283147  2016-06-24 00:00:00    FALSE
 4 12807410  2016-08-08 00:00:00    FALSE
 5 13600637  2016-08-08 00:00:00    FALSE
 6 13343064  2016-08-08 00:00:00    FALSE
 7 13256011  2016-08-16 00:00:00    FALSE
 8 12515587  2016-09-16 00:00:00    FALSE
 9 13420182  2016-09-16 00:00:00    FALSE
10 13355901  2016-10-24 00:00:00    FALSE
# ℹ 2,764 more rows

In [45]:
ch_mace_merged <- merge(x =ch_cohort, y = mace_data_filtered, all.x = TRUE)

In [46]:
ch_mace_merged$first_episodestartdate <- as_date(ch_mace_merged$first_episodestartdate)

In [47]:
ch_mace_merged <- ch_mace_merged %>% mutate(exposure_time = (date.event -first_episodestartdate))

In [48]:
 ch_mace_merged_filtered <- ch_mace_merged %>% filter(hypertension == TRUE)

In [49]:
ch_mace_merged_filtered$exposure_time <- ifelse(is.na(ch_mace_merged_filtered$exposure_time) ,365,ch_mace_merged_filtered$exposure_time)

In [50]:
ch_mace_merged_filtered <-ch_mace_merged_filtered %>%  select(-"event_id")

In [51]:
(sum(ch_mace_merged_filtered$exposure_time < 365)/(ch_mace_merged_filtered$exposure_time %>% sum()/365))*100

[1] 7.498732